/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BangLuongBUS;
import BUS.HeSoLuongBUS;
import BUS.KhenThuongKyLuatBUS;
import BUS.LuongBUS;
import BUS.NhanVienBUS;
import DTO.BangLuongDTO;
import DTO.HeSoLuongDTO;
import DTO.KhenThuongKyLuatDTO;
import DTO.LuongDTO;
import DTO.NhanVienDTO;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chicu
 */
public class FrmBangLuong extends javax.swing.JPanel {

    DefaultTableModel defaultTableModel;
    BangLuongBUS blbus;
    BangLuongDTO bldto;

    /**
     * Creates new form FrmBangLuong
     */
    public FrmBangLuong() {
        initComponents();
        blbus = new BangLuongBUS();
        bldto = new BangLuongDTO();
        getAllCBB();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
        };
        salaryTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã lương");
        defaultTableModel.addColumn("Mã nhân viên");
        defaultTableModel.addColumn("Tên nhân viên");
        defaultTableModel.addColumn("Lương cơ bản");
        defaultTableModel.addColumn("Hệ số lương");
        defaultTableModel.addColumn("Thưởng phạt");
        defaultTableModel.addColumn("Tiền lương");
        defaultTableModel.addColumn("Ngày lập bảng");
        defaultTableModel.addColumn("Ngày sửa đổi");

        setSalaryTable(blbus.getBangLuong());
    }

    public void setSalaryTable(ArrayList<BangLuongDTO> SalaryList) {
        for (BangLuongDTO SalaryItem : SalaryList) {
            defaultTableModel.addRow(new Object[]{
                SalaryItem.getMaLuong(),
                SalaryItem.getMaNV(),
                SalaryItem.getTenNV(),
                SalaryItem.getLuongCoBan(),
                SalaryItem.getHeSoLuong(),
                SalaryItem.getThuongPhat(),
                SalaryItem.getTienLuong(),
                SalaryItem.getNgayLapBang(),
                SalaryItem.getNgaySuaDoi()
            });
        }
    }

    public void getMaLuongCBB(ArrayList<LuongDTO> CBBItems) {
        MaLuongCBB.removeAllItems();
        for (LuongDTO CBBItem : CBBItems) {
            MaLuongCBB.addItem(CBBItem.getMaLuong());
        }
    }

    public void getMaNVCBB(ArrayList<NhanVienDTO> CBBItems) {
        MaNVCBB.removeAllItems();
        for (NhanVienDTO CBBItem : CBBItems) {
            MaNVCBB.addItem(CBBItem.getMaNV());
        }
    }

    public void getAllCBB() {
        LuongBUS luongBUS = new LuongBUS();
        ArrayList<LuongDTO> arrLuong = luongBUS.getLuong();
        getMaLuongCBB(arrLuong);

        NhanVienBUS nvbus = new NhanVienBUS();
        ArrayList<NhanVienDTO> arrNV = nvbus.getNhanVien();
        getMaNVCBB(arrNV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salaryTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel2.getWidth(), jPanel2.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        studyIDLabel = new javax.swing.JLabel();
        salaryAddBtn = new javax.swing.JButton();
        employeeIDLabel = new javax.swing.JLabel();
        virtualLabel = new javax.swing.JLabel();
        MaLuongCBB = new javax.swing.JComboBox<>();
        MaNVCBB = new javax.swing.JComboBox<>();
        refreshBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel1.getWidth(), jPanel1.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel3.getWidth(), jPanel3.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        LCBLabel = new javax.swing.JLabel();
        HSLLabel = new javax.swing.JLabel();

        salaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã lương", "Mã nhân viên", "Tên nhân viên", "Ngày lập bảng", "Lương cơ bản", "Hệ số lương", "Thưởng phạt", "Tiền lương", "Ngày sửa đổi"
            }
        ));
        salaryTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        salaryTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(salaryTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 600));

        studyIDLabel.setText("Mã lương:");

        salaryAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/add.png"))); // NOI18N
        salaryAddBtn.setText("Thêm");
        salaryAddBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        salaryAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryAddBtnActionPerformed(evt);
            }
        });

        employeeIDLabel.setText("Mã nhân viên");

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/refresh.png"))); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(virtualLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(studyIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(71, 71, 71))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(MaLuongCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(salaryAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(refreshBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(employeeIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(MaNVCBB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studyIDLabel)
                    .addComponent(employeeIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaLuongCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaNVCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(virtualLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(207, 24));

        jLabel1.setText("Thông tin bảng lương");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 204)));

        LCBLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LCBLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8-money-20.png"))); // NOI18N
        LCBLabel.setText("Lương căn bản");
        LCBLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 204)));
        LCBLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LCBLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LCBLabelMouseClicked(evt);
            }
        });

        HSLLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HSLLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8-coins-20.png"))); // NOI18N
        HSLLabel.setText("Hệ số lương");
        HSLLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HSLLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HSLLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LCBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HSLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LCBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(HSLLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salaryAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryAddBtnActionPerformed
        // TODO add your handling code here:
        if ("".equals(MaLuongCBB.getSelectedItem().toString()) || "".equals(MaNVCBB.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống dữ liệu nhập vào !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            bldto.setMaLuong(MaLuongCBB.getSelectedItem().toString());
            bldto.setMaNV(MaNVCBB.getSelectedItem().toString());

            blbus.addBangLuong(bldto);
            JOptionPane.showMessageDialog(this, "Thêm lương thành công !!!");
            defaultTableModel.setRowCount(0);
            setSalaryTable(blbus.getBangLuong());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_salaryAddBtnActionPerformed
    
    public FrmMain frmMain;

    public void showLCB(JLabel btn) {
        JDialog dialog = new JDialog(frmMain, "Thông tin lương căn bản", true);
        dialog.setSize(908, 594);
        dialog.setLocationRelativeTo(null);
        dialog.add(new FrmLuongCanBan(btn, dialog));
        dialog.setVisible(true);
    }
    
    public void showHSL(JLabel btn) {
        JDialog dialog = new JDialog(frmMain, "Thông tin hệ số lương", true);
        dialog.setSize(908, 594);
        dialog.setLocationRelativeTo(null);
        dialog.add(new FrmHeSoLuong(btn, dialog));
        dialog.setVisible(true);
    }
    
    private void LCBLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LCBLabelMouseClicked
        // TODO add your handling code here:
        showLCB(LCBLabel);
    }//GEN-LAST:event_LCBLabelMouseClicked

    private void HSLLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HSLLabelMouseClicked
        // TODO add your handling code here:
        showHSL(HSLLabel);
    }//GEN-LAST:event_HSLLabelMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        setSalaryTable(blbus.getBangLuong());
        getAllCBB();
    }//GEN-LAST:event_refreshBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HSLLabel;
    private javax.swing.JLabel LCBLabel;
    private javax.swing.JComboBox<String> MaLuongCBB;
    private javax.swing.JComboBox<String> MaNVCBB;
    private javax.swing.JLabel employeeIDLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton salaryAddBtn;
    private javax.swing.JTable salaryTable;
    private javax.swing.JLabel studyIDLabel;
    private javax.swing.JLabel virtualLabel;
    // End of variables declaration//GEN-END:variables
}
