/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.HeSoLuongBUS;
import DTO.HeSoLuongDTO;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chicu
 */
public class FrmHeSoLuong extends javax.swing.JPanel {

    HeSoLuongBUS hslbus;
    HeSoLuongDTO hsldto;
    DefaultTableModel defaultTableModel;
    JLabel label;
    JDialog dialog;
    /**
     * Creates new form FrmHeSoLuong
     */
    public FrmHeSoLuong(JLabel label, JDialog dialog) {
        initComponents();
        this.label = label;
        this.dialog = dialog;
        hslbus = new HeSoLuongBUS();
        hsldto = new HeSoLuongDTO();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
        };
        dataTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã hệ số lương");
        defaultTableModel.addColumn("hệ số lương");
        setHSL(hslbus.getHeSoLuong());
    }

    public void setHSL(ArrayList<HeSoLuongDTO> HSLs) {
        for (HeSoLuongDTO HSL : HSLs) {
            defaultTableModel.addRow(new Object[]{
                HSL.getMaHSL(),
                HSL.getHeSoLuong()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel2.getWidth(), jPanel2.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        studyIDLabel = new javax.swing.JLabel();
        HSLIDField = new javax.swing.JTextField();
        HSLField = new javax.swing.JTextField();
        HSLDeleteBtn = new javax.swing.JButton();
        HSLSaveBtn = new javax.swing.JButton();
        HSLCancelBtn = new javax.swing.JButton();
        HSLAddBtn = new javax.swing.JButton();
        studyNameLabel = new javax.swing.JLabel();
        virtualLabel = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        inputField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel1.getWidth(), jPanel1.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        jLabel1 = new javax.swing.JLabel();
        selectBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Hệ số lương", "Hệ số lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(dataTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 600));

        studyIDLabel.setText("Mã HSL:");

        HSLDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/xoa.png"))); // NOI18N
        HSLDeleteBtn.setText("Xóa");
        HSLDeleteBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        HSLDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSLDeleteBtnActionPerformed(evt);
            }
        });

        HSLSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/sua.png"))); // NOI18N
        HSLSaveBtn.setText("Sửa");
        HSLSaveBtn.setEnabled(false);
        HSLSaveBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        HSLSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSLSaveBtnActionPerformed(evt);
            }
        });

        HSLCancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/huy.png"))); // NOI18N
        HSLCancelBtn.setText("Hủy");
        HSLCancelBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        HSLCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSLCancelBtnActionPerformed(evt);
            }
        });

        HSLAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/add.png"))); // NOI18N
        HSLAddBtn.setText("Thêm");
        HSLAddBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        HSLAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSLAddBtnActionPerformed(evt);
            }
        });

        studyNameLabel.setText("Hệ số lương:");

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/search.png"))); // NOI18N
        searchBtn.setText("Tìm kiếm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập mã HSL cần tìm:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studyNameLabel)
                            .addComponent(studyIDLabel)
                            .addComponent(HSLIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HSLField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(virtualLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HSLAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HSLSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HSLDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HSLCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(searchBtn)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(studyIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HSLIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studyNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HSLField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(virtualLabel)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HSLAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HSLDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HSLCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HSLSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(207, 24));

        jLabel1.setText("Thông tin hệ số lương");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        selectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/chon.png"))); // NOI18N
        selectBtn.setText("Chọn");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/refresh.png"))); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectBtn)
                            .addComponent(refreshBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HSLDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSLDeleteBtnActionPerformed
        // TODO add your handling code here:
        int row = dataTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hệ số lương cần xóa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không ?");

                if (confirm == JOptionPane.YES_OPTION) {
                    String HSLCode = String.valueOf(dataTable.getValueAt(row, 0));
                    hslbus.deleteHeSoLuong(HSLCode);
                    defaultTableModel.setRowCount(0);
                    setHSL(hslbus.getHeSoLuong());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_HSLDeleteBtnActionPerformed

    private void HSLSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSLSaveBtnActionPerformed
        // TODO add your handling code here:
        int row = dataTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hệ số lương cần sửa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            try {
                hsldto.setMaHSL(HSLIDField.getText());
                hsldto.setHeSoLuong(Double.parseDouble(HSLField.getText()));
                hslbus.updateHeSoLuong(hsldto);
                JOptionPane.showMessageDialog(this, "Sửa hệ số lương thành công !!!");
                defaultTableModel.setRowCount(0);
                setHSL(hslbus.getHeSoLuong());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hệ số lương bạn vừa nhập không phải là số, vui lòng nhập đúng !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_HSLSaveBtnActionPerformed

    private void HSLCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSLCancelBtnActionPerformed
        // TODO add your handling code here:
        HSLIDField.setText("");
        HSLField.setText("");
        HSLIDField.setEnabled(true);
        HSLSaveBtn.setEnabled(false);
    }//GEN-LAST:event_HSLCancelBtnActionPerformed

    private void HSLAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSLAddBtnActionPerformed
        // TODO add your handling code here:
        if ("".equals(HSLIDField.getText()) || "".equals(HSLField.getText())) {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống dữ liệu nhập vào !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            hsldto.setMaHSL(HSLIDField.getText());
            try {
                hsldto.setHeSoLuong(Double.parseDouble(HSLField.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hệ số lương bạn vừa nhập không phải là số, vui lòng nhập đúng !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            hslbus.addHeSoLuong(hsldto);
            JOptionPane.showMessageDialog(this, "Thêm hệ số lương thành công !!!");
            defaultTableModel.setRowCount(0);
            setHSL(hslbus.getHeSoLuong());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Mã hệ số lương bị trùng", "Lỗi", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_HSLAddBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String input = inputField.getText().trim();
        if ("".equals(inputField.getText())) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã KTKL cầm tìm !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        dataTable.removeAll();
        defaultTableModel.setRowCount(0);
        setHSLDataByID(hslbus.getHeSoLuong(), input);
    }//GEN-LAST:event_searchBtnActionPerformed

    public void setHSLDataByID(ArrayList<HeSoLuongDTO> HSLs, String MaHSL) {
        for (HeSoLuongDTO HSL : HSLs) {
            MaHSL = MaHSL.toLowerCase();
            if (HSL.getMaHSL().toLowerCase().equals(MaHSL)) {
                defaultTableModel.addRow(new Object[]{
                    HSL.getMaHSL(),
                    HSL.getHeSoLuong(),});
            }
        }
    }

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        showInfo();
        HSLSaveBtn.setEnabled(true);
    }//GEN-LAST:event_selectBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        setHSL(hslbus.getHeSoLuong());
    }//GEN-LAST:event_refreshBtnActionPerformed

    public void showInfo() {
        int row = dataTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hệ số lương cần sửa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String HSLCode = String.valueOf(dataTable.getValueAt(row, 0));
            hsldto = hslbus.findHSLbyID(HSLCode);
            HSLIDField.setText(hsldto.getMaHSL());
            HSLIDField.setEnabled(false);
            HSLField.setText(String.valueOf(hsldto.getHeSoLuong()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HSLAddBtn;
    private javax.swing.JButton HSLCancelBtn;
    private javax.swing.JButton HSLDeleteBtn;
    private javax.swing.JTextField HSLField;
    private javax.swing.JTextField HSLIDField;
    private javax.swing.JButton HSLSaveBtn;
    private javax.swing.JTable dataTable;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    private javax.swing.JLabel studyIDLabel;
    private javax.swing.JLabel studyNameLabel;
    private javax.swing.JLabel virtualLabel;
    // End of variables declaration//GEN-END:variables
}
