/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.KhenThuongKyLuatBUS;
import DAO.KhenThuongKyLuatDAO;
import DTO.KhenThuongKyLuatDTO;
import Exception.AllException;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chicu
 */
public class FrmKTKL extends javax.swing.JPanel {
    KhenThuongKyLuatDTO ktklDTO;
    KhenThuongKyLuatBUS ktklBUS;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form FrmKTKL
     */
    public FrmKTKL() {
        initComponents();
        ktklDTO = new KhenThuongKyLuatDTO();
        ktklBUS = new KhenThuongKyLuatBUS();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
        };
        dataTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã KTKL");
        defaultTableModel.addColumn("Số tiền");
        defaultTableModel.addColumn("Ngày quyết định");
        defaultTableModel.addColumn("Loại quyết định");
        defaultTableModel.addColumn("Nội dung");
        defaultTableModel.addColumn("Ngày sửa đổi");
        setKTKLData(ktklBUS.getKhenThuongKyLuat());
    }
    
    public void setKTKLData(ArrayList<KhenThuongKyLuatDTO> KTKLs) {
        for (KhenThuongKyLuatDTO KTKL : KTKLs) {
            defaultTableModel.addRow(new Object[]{
                KTKL.getMaKTKL(),
                KTKL.getSoTien(),
                KTKL.getNgayQuyetDinh(),
                KTKL.getLoaiQuyetDinh(),
                KTKL.getNoiDung(),
                KTKL.getNgaySuaDoi()
            });
        }
    }
    
    public FrmMain frmMain;
    
    public void showSearchField(JButton btn) {
        JDialog dialog = new JDialog(frmMain, "Tìm kiếm", true);
        dialog.setSize(908, 594);
        dialog.setLocationRelativeTo(null);
        dialog.add(new FrmTimKTKL(btn, dialog));
        dialog.setVisible(true);
    }
    
    public void showInfoField(JButton btn) {
        JDialog dialog = new JDialog(frmMain, "Chi tiết", true);
        dialog.setSize(700, 500);
        dialog.setLocationRelativeTo(null);
        dialog.add(new FrmChiTietKTKL(btn, dialog));
        dialog.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel1.getWidth(), jPanel1.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel2.getWidth(), jPanel2.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        studyIDLabel = new javax.swing.JLabel();
        KTKLIDField = new javax.swing.JTextField();
        KTKLMoneyField = new javax.swing.JTextField();
        KTKLDeleteBtn = new javax.swing.JButton();
        KTKLSaveBtn = new javax.swing.JButton();
        KTKLCancelBtn = new javax.swing.JButton();
        KTKLAddBtn = new javax.swing.JButton();
        studyNameLabel = new javax.swing.JLabel();
        virtualLabel = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        KTKLCBB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KTKLtxtArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        selectBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(207, 24));

        jLabel1.setText("Thông tin khen thưởng kỷ luật");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 600));

        studyIDLabel.setText("Mã KTKL:");

        KTKLDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/xoa.png"))); // NOI18N
        KTKLDeleteBtn.setText("Xóa");
        KTKLDeleteBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        KTKLDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KTKLDeleteBtnActionPerformed(evt);
            }
        });

        KTKLSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/sua.png"))); // NOI18N
        KTKLSaveBtn.setText("Sửa");
        KTKLSaveBtn.setEnabled(false);
        KTKLSaveBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        KTKLSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KTKLSaveBtnActionPerformed(evt);
            }
        });

        KTKLCancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/huy.png"))); // NOI18N
        KTKLCancelBtn.setText("Hủy");
        KTKLCancelBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        KTKLCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KTKLCancelBtnActionPerformed(evt);
            }
        });

        KTKLAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/add.png"))); // NOI18N
        KTKLAddBtn.setText("Thêm");
        KTKLAddBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        KTKLAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KTKLAddBtnActionPerformed(evt);
            }
        });

        studyNameLabel.setText("Số tiền:");

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/search.png"))); // NOI18N
        searchBtn.setText("Tìm kiếm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Loại quyết định:");

        KTKLCBB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khen thưởng", "Kỷ luật" }));

        jLabel3.setText("Nội dung:");

        KTKLtxtArea.setColumns(20);
        KTKLtxtArea.setRows(5);
        jScrollPane1.setViewportView(KTKLtxtArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchBtn)
                .addGap(69, 69, 69))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studyNameLabel)
                            .addComponent(studyIDLabel)
                            .addComponent(KTKLIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KTKLMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(virtualLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(KTKLCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KTKLAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KTKLSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KTKLDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KTKLCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(studyIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KTKLIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studyNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KTKLMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(virtualLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KTKLCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KTKLAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KTKLDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KTKLCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KTKLSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn)
                .addContainerGap())
        );

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(dataTable);

        selectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/chon.png"))); // NOI18N
        selectBtn.setText("Chọn");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8-info-20.png"))); // NOI18N
        infoBtn.setText("Chi tiết");
        infoBtn.setToolTipText("");
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectBtn)
                            .addComponent(infoBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void KTKLDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KTKLDeleteBtnActionPerformed
        // TODO add your handling code here:
        int row = dataTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn bảng KTKL cần xóa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không ?");

            if (confirm == JOptionPane.YES_OPTION) {
                String KTKLCode = String.valueOf(dataTable.getValueAt(row, 0));
                
                try {
                    ktklBUS.deleteKhenThuongKyLuat(KTKLCode);
                } catch (AllException ex) {
                    JOptionPane.showMessageDialog(this, ex,"Lỗi",JOptionPane.ERROR_MESSAGE);
                }
                defaultTableModel.setRowCount(0);
                setKTKLData(ktklBUS.getKhenThuongKyLuat());
            }
        }
    }//GEN-LAST:event_KTKLDeleteBtnActionPerformed

    private void KTKLSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KTKLSaveBtnActionPerformed
        // TODO add your handling code here:
        int row = dataTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khen thưởng kỷ luật cần sửa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            ktklDTO.setMaKTKL(KTKLIDField.getText());
            ktklDTO.setSoTien(Double.parseDouble(KTKLMoneyField.getText()));
            ktklDTO.setLoaiQuyetDinh(KTKLCBB.getSelectedItem().toString());
            ktklDTO.setNoiDung(KTKLtxtArea.getText());
            
            ktklBUS.updateKhenThuongKyLuat(ktklDTO);
            JOptionPane.showMessageDialog(this, "Sửa khen thưởng kỷ luật thành công !!!");
            defaultTableModel.setRowCount(0);
            setKTKLData(ktklBUS.getKhenThuongKyLuat());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_KTKLSaveBtnActionPerformed

    private void KTKLCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KTKLCancelBtnActionPerformed
        // TODO add your handling code here:
        KTKLIDField.setText("");
        KTKLMoneyField.setText("");
        KTKLIDField.setEnabled(true);
        KTKLSaveBtn.setEnabled(false);
        KTKLtxtArea.setText("");
    }//GEN-LAST:event_KTKLCancelBtnActionPerformed

    private void KTKLAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KTKLAddBtnActionPerformed
        // TODO add your handling code here:
        if ("".equals(KTKLIDField.getText()) || "".equals(KTKLMoneyField.getText()) || "".equals(KTKLtxtArea.getText())) {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống dữ liệu nhập vào !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            ktklDTO.setMaKTKL(KTKLIDField.getText());
            ktklDTO.setSoTien(Double.parseDouble(KTKLMoneyField.getText()));
            ktklDTO.setLoaiQuyetDinh(KTKLCBB.getSelectedItem().toString());
            ktklDTO.setNoiDung(KTKLtxtArea.getText());
            
            ktklBUS.addKhenThuongKyLuat(ktklDTO);
            JOptionPane.showMessageDialog(this, "Thêm khen thưởng kỷ luật thành công !!!");
            defaultTableModel.setRowCount(0);
            setKTKLData(ktklBUS.getKhenThuongKyLuat());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);

        }
    }//GEN-LAST:event_KTKLAddBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        showSearchField(searchBtn);
    }//GEN-LAST:event_searchBtnActionPerformed

    public void showInfo() {
        int row = dataTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khen thưởng kỷ luật cần sửa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String KTKLCode = String.valueOf(dataTable.getValueAt(row, 0));
            ktklDTO = ktklBUS.getKTKLByID(KTKLCode);
            KTKLIDField.setText(ktklDTO.getMaKTKL());
            KTKLIDField.setEnabled(false);
            KTKLMoneyField.setText(String.valueOf(ktklDTO.getSoTien()));
            KTKLCBB.setSelectedItem(ktklDTO.getLoaiQuyetDinh());
            KTKLtxtArea.setText(ktklDTO.getNoiDung());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
        }
    }
    
    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        showInfo();
        KTKLSaveBtn.setEnabled(true);
    }//GEN-LAST:event_selectBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        // TODO add your handling code here:
        showInfoField(infoBtn);
    }//GEN-LAST:event_infoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KTKLAddBtn;
    private javax.swing.JComboBox<String> KTKLCBB;
    private javax.swing.JButton KTKLCancelBtn;
    private javax.swing.JButton KTKLDeleteBtn;
    private javax.swing.JTextField KTKLIDField;
    private javax.swing.JTextField KTKLMoneyField;
    private javax.swing.JButton KTKLSaveBtn;
    private javax.swing.JTextArea KTKLtxtArea;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    private javax.swing.JLabel studyIDLabel;
    private javax.swing.JLabel studyNameLabel;
    private javax.swing.JLabel virtualLabel;
    // End of variables declaration//GEN-END:variables
}
